### ISSUE TITLE
Exposing editable.js as AMD

### ISSUE THREAD

**Issue by viswesh** [livingdocsIO/editable.js#154]
Thank you for your efforts in developing and maintaining this library. 

Related issue - https://github.com/upfrontIO/editable.js/issues/103

I'm using version v0.6.2 (before ES2015 rewrite) with require js and bundling editable in a separate layer.
```
paths: { 
   "jquery": "vendor", 
   "backbone": "vendor", 
   "underscore": "vendor", 
   "Editable": "app"
 }
```
In the unminified version, require js is able to resolve Editable as the shim points to 'Editable' available at window.Editable. But in the minified app generated by r.js (require js optimizer), the app stops working due to Editable module timeout. In other words, require js is unable to resolve Editable.

Based on @peyerluk  suggestion, I ran 'grunt dev' to extract only the editable library (which is generated at .tmp/). This didn't work as well as - I get the following error -
```
Uncaught ReferenceError: $ is not defined 
   at app.js?t=20160320000000:3661 
   at Object.21../config (app.js?t=20160320000000:3928)
```
$ does not point to the window.$, hence it errors out. Including jquery at the top of editable.js works but that's just patchwork from my side.
```
Selection.prototype = $.extend(new Base(), {
```
Is there a way I can just use 'Editable' ES5 version? I can perhaps pull in rangy and bowser separately? 

As an alternative, I looked at /lib from version 1.0.0 (ES2015) but how do I consume it? I just need a single 'editable.js' only file which is ES5.

**Comment by peyerluk** [comment]
`jQuery` is only a peer dependency that's probably causing the issues. Running `npm install jquery` before running `grunt dev` may solve the issue.

**Comment by viswesh** [comment]
I should have been more clear. I was getting the '$ is not defined' during run-time, not during build. I was able to progress by making sure jQuery is loaded before Editable loads at run time. 

As next steps, to replicate examples directory mentioned at #103 , I loaded only Editable (bowser included). Rangy is loaded before Editable loads - 
```
paths: { 
   "jquery": "vendor", 
   "backbone": "vendor", 
   "underscore": "vendor",
   "rangy": "vendor", 
   "Editable": "app"
}
```

```
shim: {
"rangy": {
           "deps": ["jquery"],
            exports: "rangy"
        },
        "Editable": {            
            "deps": ["jquery", "rangy"],
            exports: "Editable" // exporting Editable
        }
}

```
This setup resulted in the same error:

```
Stack trace: Error: Load timeout for modules: Editable
http://requirejs.org/docs/errors.html#timeout
    at makeError (https://localhost/assets/js/vendor/require/require.js:168:17)
    at checkLoaded (https://localhost/assets/js/vendor/require/require.js:698:23)
    at https://localhost/assets/js/vendor/require/require.js:719:25
```
Based on require.js documentation for module timeouts, the potential issues can be - 
1. Errors in one of the listed modules
2. Incorrect paths in config
3. Multiple module ids pointing to same file.
 
I don’t think its 2. or 3. because the paths are correct and there are no multiple ids pointing to the same file (It's a small test bed I'm running this against). 

How can I move forward? Your expertise is greatly appreciated!

**Comment by viswesh** [comment]
Any suggestions?

**Comment by marcbachmann** [comment]
I think we can close this as we've removed jQuery completely.
