### ISSUE TITLE
Switch event not firing?

### ISSUE THREAD

**Issue by BryceBubbles** [livingdocsIO/editable.js#161]
The documented switch event doesn't seem to fire.
I think tab, shift+tab and arrows do their default actions.

All other documented events work as expected.

**Comment by BryceBubbles** [comment]
Looks like the switch event is only dispatched if the cursor stays in the same position on arrow press.
https://github.com/livingdocsIO/editable.js/blob/c2107cc2182d54f64322c744d7853aec6301cc38/src/dispatcher.js#L170-L179
I'm guessing `newCursor.equals(cursor)` is always false for some reason.
I haven't been able to look into why this might be yet.

**Comment by peyerluk** [comment]
This is fixed now.
