### ISSUE TITLE
remove jQuery as a dependency

### ISSUE THREAD

**Issue by TorstenDittmann** [livingdocsIO/editable.js#197]
I can work on removing jQuery as a peer Dependency.

A major part of the jQuery methods used can be easily replaced, some probably need some extra helpers like `closest()`.

Any objections or known issues regarding that topic?

**Comment by peyerluk** [comment]
Yes, please!

This is in our the backlog for ages :) 

It might help to split up the work into multiple PRs so we can get rid of the easy cases first. And please tell me if there are cases where additional tests would help.

**Comment by TorstenDittmann** [comment]
Alright 👍 

Do you mind creating a dedicated branch for these PRs?

Will most likely start working on this by friday 🙂

**Comment by peyerluk** [comment]
I created the branch `sans-jquery` https://github.com/livingdocsIO/editable.js/tree/sans-jquery.

**Comment by jenstroeger** [comment]
@TorstenDittmann, happy to help 👍

**Comment by TorstenDittmann** [comment]
Removed jQuery in a bunch of files here #200 

I am quite confused about [this method here](https://github.com/livingdocsIO/editable.js/blob/98f3b42ab646e99493c58ee8c37b31806689b30d/src/content.js#L297-L304).
It get's an empty tag in `elem` and with some magic it removes surrounding tags without any context to the editors content. Maybe it was too late for me, gonna have to look again later 👍 

I also faced THE biggest hurdle with removing jQuery, eventhandler 😨 

Since jQuery does some cool stuff like removing events with namespace strings & co, solving this will end up as a small library handling all DOM events inside editable.js. Annoying , but doable 🙂

**Comment by jenstroeger** [comment]
This is going to be a breaking interface change, because several function arguments change from jQuery object to plain DOM elements. Will users have to port code, or will the new code supply guards like
```javascript
if (obj instanceof jQuery) {
  // assert obj.length === 1
  obj = obj[0]
}
```

> Annoying , but doable 🙂

Have you looked at the [jQuery code](https://github.com/jquery/jquery/tree/master/src) to maybe lift some functions from there?

> This might be something where I might need a little help with planning from @jenstroeger 😉

Anything in particular?

**Comment by TorstenDittmann** [comment]
> This is going to be a breaking interface change, because several function arguments change from jQuery object to plain DOM elements. Will users have to port code, or will the new code supply guards like
> 
> ```js
> if (obj instanceof jQuery) {
>   // assert obj.length === 1
>   obj = obj[0]
> }
> ```

Gonna keep that in mind, but can easily be added afterwards until this is properly discussed.

> Also, uses of jQuery’s [data()](https://api.jquery.com/jQuery.data/) will be modeled how… as [data attributes](https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes) or [dataset property](https://developer.mozilla.org/en-US/docs/Web/API/HTMLOrForeignElement/dataset)?

I would prefer data-attributes 🤔 

> > This might be something where I might need a little help with planning from @jenstroeger 😉
> 
> Anything in particular?

Well, planned something out already. I might have overrated that issue when I wrote that comment. Gonna write a service that holds and manages all the DOM events.

**Comment by jenstroeger** [comment]
> Gonna keep that in mind, but can easily be added afterwards until this is properly discussed.

There’s already a single similar guard:

https://github.com/livingdocsIO/editable.js/blob/373d654c0cc214a4430bcc067a7e53b583224e41/src/cursor.js#L228

**Comment by marcbachmann** [comment]
#221
