### ISSUE TITLE
Cursor event doesn’t always move blocks.

### ISSUE THREAD

**Issue by jenstroeger** [livingdocsIO/editable.js#244]
Using Chrome I get the following sequence of events on the example page by navigating the cursor up or down the [contenteditable](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/contenteditable) paragraph:

![chrome](https://user-images.githubusercontent.com/12053937/135983825-4ccb4786-f094-4601-b395-cbb14ad05133.jpg)

This behavior begins to change when I zoom the page, e.g. I don’t get the “Set the focus to the following block” when I zoom to 110% or 90% — I suspect that zoom messes with the bounding box of the host element when the [curser detects whether its on the last line](https://github.com/livingdocsIO/editable.js/blob/ad5e43330e0f2b32687c86346775766167593cb5/src/cursor.js#L93-L100)?

With Safari (I’m using v14.0.1) and not even using zoom, however, I don’t see _any_ of these events:

![safari](https://user-images.githubusercontent.com/12053937/135984466-a1e53806-6a4a-4454-a43e-409af5563c62.jpg)

Instead, the cursor just jumps to the beginning (when moving “up”) or the end (when moving “down”) of the host element.

**Comment by marcbachmann** [comment]
Ohhh, this fix looked too good in that case https://github.com/livingdocsIO/editable.js/commit/5687b0ffc0e2813f259931dca4a6e95859876c23
The first implementation did not work with newlines at all.
Maybe there's some rounding error with some calculation?
Right, safari also doesn't work for me.

**Comment by marcbachmann** [comment]
It's definitely some rounding issue in chrome.
Another issue in safari.
```js
# Chrome
## without zoom
isAtFirstLine: top: host = 222.578125, cursor = 222.578125
isAtLastLine: bottom: host = 192.984375, cursor = 192.984375

## with zoom
isAtLastLine: bottom: host = 264.4701232910156, cursor = 328.8179397583008
isAtFirstLine: top: host = 222.4857940673828, cursor = 222.4857940673828


# Safari
## without zoom
isAtFirstLine: top: host = 353, cursor = 355
isAtLastLine: bottom: host = 263, cursor = 326

## with zoom
isAtFirstLine: top: host = 356.2907409667969, cursor = 358.8994445800781
isAtLastLine: bottom: host = 264.4701232910156, cursor = 328.8179397583008

```

**Comment by marcbachmann** [comment]
In safari the newlines case an issue.
This doesn't work:
```html
<p>
  Hello
</p>
<p>
  World
</p>
```

And this is working:
```html
<p>Hello</p>
<p>World</p>
```

**Comment by marcbachmann** [comment]
It's only partially solved. We might need to fix the `content.tidyHtml(elem)` function to fix it completely for safari. Newlines (and empty text nodes) at the start and end of a block should get removed.

**Comment by marcbachmann** [comment]
Similar to the `extractContent` functions: https://github.com/livingdocsIO/editable.js/blame/master/src/content.js#L93-L97
