### ISSUE TITLE
First `change` event has old element instance

### ISSUE THREAD

**Issue by NelsonBrandao** [livingdocsIO/editable.js#488]
The first `change` event triggered has an old version of the element. This results on the change being missed. Further `change` events appear to be working correctly.

This can be seen on demo provided by this package:

https://github.com/livingdocsIO/editable.js/assets/1036806/96267ce7-fc79-42d0-8ae3-0ed7941b9712

The first time we type `1` the output below doesn't get updated.

**Comment by marcbachmann** [comment]
Thanks for reporting this.
It's caused by some backwards compatibilty support of older browsers and we can remove this by now.

I also just ran into the same issue when running e2e tests.
