### ISSUE TITLE
Merging through backspace does not work all the time.

### ISSUE THREAD

**Issue by peyerluk** [livingdocsIO/editable.js#72]
Pressing backspace at the beginning of a paragraph does not always work.  

Reproduce: 
- Fire up the editable test site in Chrome
- Place the cursor at the beginning of the second block paragraph
- Press backspace

Expected behaviour:
- The second and first paragraph should get merged

Observed behaviour:
- Nothing happens at all. Even if pressing backspace repeatedly.

**Comment by mokimo** [comment]
Closing this one as it seems outdated
