### ISSUE TITLE
Executing CMD+b on a selected text creates a <strong> tag

### ISSUE THREAD

**Issue by marcbachmann** [livingdocsIO/editable.js#89]
... which can't be removed by a user if editable.js is configured to use `<b>` tags.

**Comment by benib** [comment]
It would be awesome if editable could make sure that CMD+b results in `<b>` instead of `<strong>` if configured to use `<b>`.

**Comment by benib** [comment]
-> https://github.com/livingdocsIO/livingdocs-planning/issues/4185
